name: Dependency Submission

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - uses: gradle/actions/dependency-submission@v4
